"""Сокращения, по которым вузы ищут чаще, чем по полному названию.

Это словарь поисковых подсказок, а не список вузов: каждое сокращение
разворачивается в запрос к Wikidata, итоговая сущность всё равно ищется там.
"""
from __future__ import annotations

ALIASES: dict[str, list[str]] = {
    "ену": ["Евразийский национальный университет", "L. N. Gumilyov Eurasian National University"],
    "еұу": ["Еуразия ұлттық университеті", "Eurasian National University"],
    "enu": ["L. N. Gumilyov Eurasian National University"],
    "казну": ["Казахский национальный университет имени аль-Фараби", "Al-Farabi Kazakh National University"],
    "kaznu": ["Al-Farabi Kazakh National University"],
    "кбту": ["Казахстанско-Британский технический университет", "Kazakh-British Technical University"],
    "kbtu": ["Kazakh-British Technical University"],
    "муит": ["Международный университет информационных технологий", "International Information Technology University"],
    "iitu": ["International Information Technology University"],
    "sdu": ["Suleyman Demirel University", "SDU University"],
    "сду": ["Suleyman Demirel University"],
    "aitu": ["Astana IT University"],
    "аиту": ["Astana IT University"],
    "nu": ["Nazarbayev University"],
    "ну": ["Nazarbayev University"],
    "назарбаев": ["Nazarbayev University"],
    "казниту": ["Satbayev University", "Казахский национальный исследовательский технический университет имени К. И. Сатпаева"],
    "satbayev": ["Satbayev University"],
    "сатпаев": ["Satbayev University"],
    "кимэп": ["KIMEP University"],
    "kimep": ["KIMEP University"],
    "казгюу": ["Maqsut Narikbayev University"],
    "mnu": ["Maqsut Narikbayev University"],
    "казату": ["Казахский агротехнический исследовательский университет имени Сакена Сейфуллина", "S. Seifullin Kazakh Agro Technical Research University"],
    "нархоз": ["Narxoz University"],
    "narxoz": ["Narxoz University"],
    "ауэс": ["Алматинский университет энергетики и связи"],
    "карагу": ["Карагандинский университет имени Е. А. Букетова"],
    "кару": ["Карагандинский университет имени Е. А. Букетова"],
    "юку": ["Южно-Казахстанский университет имени М. Ауэзова"],
    "мгу": ["Московский государственный университет имени М. В. Ломоносова"],
    "msu": ["Moscow State University"],
    "мфти": ["Московский физико-технический институт"],
    "mipt": ["Moscow Institute of Physics and Technology"],
    "вшэ": ["Высшая школа экономики"],
    "hse": ["Higher School of Economics"],
    "спбгу": ["Санкт-Петербургский государственный университет"],
    "мифи": ["Национальный исследовательский ядерный университет «МИФИ»"],
    "mit": ["Massachusetts Institute of Technology"],
    "мит": ["Massachusetts Institute of Technology"],
    "nus": ["National University of Singapore"],
    "ntu": ["Nanyang Technological University"],
    "eth": ["ETH Zurich"],
    "tum": ["Technical University of Munich"],
    "ucl": ["University College London"],
    "kaist": ["KAIST"],
    "нгу": ["Новосибирский государственный университет"],
    "ктму": ["Кыргызско-Турецкий университет «Манас»"],
    "аууца": ["Американский университет в Центральной Азии"],
    "auca": ["American University of Central Asia"],
    "инха": ["Inha University in Tashkent"],
    "wiut": ["Westminster International University in Tashkent"],
}
